apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 7afdb56d-4c21-45fc-bf94-2e9518e1d148
  labels:
    azure.workload.identity/use: "true"