apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: catalog-serviceaccount
      containers:
        - name: catalog
          image: playeconomyacr.azurecr.io/play.catalog:1.0.3
          securityContext: # temp
            runAsUser: 0
            privileged: true
          env:
            - name: ASPNETCORE_URLS # temp
              value: "http://+:5000"
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: economykeyvault
            - name: ServiceSettings__Authority
              value: https://playeconomy-gateway.westus2.cloudapp.azure.com/identity/svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5000
          # Health Probes if needed...

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 7afdb56d-4c21-45fc-bf94-2e9518e1d148
  labels:
    azure.workload.identity/use: "true"
