microserviceName: "catalog"

# docker image
image:
  repository: playeconomyacr.azurecr.io/play.catalog
  tag: 1.0.4

# Dictionary of Enviroment Variables
envVariables:
  ASPNETCORE_URLS: "http://+:5000"
  ServiceSettings__Authority: https://playeconomy-gateway.westus2.cloudapp.azure.com/identity/svc

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

# Container specifications
container:
  port: 5000

identityClientId: 7afdb56d-4c21-45fc-bf94-2e9518e1d148
